/* address in CCS format. So they must always be even numbers */
#define I2C_ADDR_APRS_PZPOWERI2C                0x34

#define I2C_ADDR_APRS_VOLTAGE_CURRENT_COUNTER_0 0x36
#define I2C_ADDR_APRS_VOLTAGE_CURRENT_COUNTER_1 0x38
#define I2C_ADDR_APRS_VOLTAGE_CURRENT_COUNTER_2 0x3a
#define I2C_ADDR_APRS_VOLTAGE_CURRENT_COUNTER_3 0x3c

#define I2C_ADDR_APRS_LATCHING_CONTACT_LVD_2X   0x3e
#define I2C_ADDR_APRS_LATCHING_CONTACT_LVD_2X   0x40
#define I2C_ADDR_APRS_LATCHING_CONTACT_LVD_2X   0x42
#define I2C_ADDR_APRS_LATCHING_CONTACT_LVD_2X   0x44


#define I2C_ADDR_NXP_SC16IS740                  0x9a

#define I2C_ADDR_DALLAS_DS1307                  0xd0
